name: AccountSystem
version: @version@
authors:
  - Azodox_
  - Virtual
main: net.valneas.account.AccountSystem
commands:
  rank:
    description: Add/Remove/Show ranks from a player
  account:
    description: Manage accounts
  permission:
    description: Manage permissions
    usage: '/permission <add/remove/show> <target> [permission]'
